// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEy5_L-FbUIKhORmyMqObng_8vd0fAE0',
    appId: '1:681232325996:web:1677cf9bdd16802f62a749',
    messagingSenderId: '681232325996',
    projectId: 'fitness-app-37a64',
    authDomain: 'fitness-app-37a64.firebaseapp.com',
    storageBucket: 'fitness-app-37a64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutKByJu-S2Kp9TAc76PD4cGF5bz2uuRc',
    appId: '1:681232325996:android:331f2de1a74ded0462a749',
    messagingSenderId: '681232325996',
    projectId: 'fitness-app-37a64',
    storageBucket: 'fitness-app-37a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZaQiAPnim1Jtq1ek5qt-XijO0jRHH5Lg',
    appId: '1:681232325996:ios:74d6ed24f06a939762a749',
    messagingSenderId: '681232325996',
    projectId: 'fitness-app-37a64',
    storageBucket: 'fitness-app-37a64.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZaQiAPnim1Jtq1ek5qt-XijO0jRHH5Lg',
    appId: '1:681232325996:ios:74d6ed24f06a939762a749',
    messagingSenderId: '681232325996',
    projectId: 'fitness-app-37a64',
    storageBucket: 'fitness-app-37a64.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNEy5_L-FbUIKhORmyMqObng_8vd0fAE0',
    appId: '1:681232325996:web:82f9d6f96bc2eec762a749',
    messagingSenderId: '681232325996',
    projectId: 'fitness-app-37a64',
    authDomain: 'fitness-app-37a64.firebaseapp.com',
    storageBucket: 'fitness-app-37a64.firebasestorage.app',
  );

}